<script src="https://cdn.jsdelivr.net/npm/signature_pad@4.0.0/dist/signature_pad.umd.min.js"></script>

<div id="header-modal" class="modal fade bs-example-modal-lg" data-bs-backdrop="static"  tabindex="-1" aria-labelledby="myLargeModalLabel" style="display: none;" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="text-center mt-4 border-bottom pb-3">
        <h5 class="modal-title">Drop-co Terms and Conditions document. Every Section needs Accept</h5>
      </div>

      <div class="modal-body">
        <p>CAREFULLY READ THESE TERMS AND CONDITIONS BEFORE ACCEPTING THEMAND USING ANY SERVICES ON THIS WEBSITE. THESE TERMS AND CONDITIONS REPLACE AND SUPERSEDE ALL PREVIOUS TERMS AND CONDITIONS. THESE TERMS AND CONDITIONS CONTAIN IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, OBLIGATIONS AND DISPUTE RESOLUTION PROCEDURES. BY USING OUR SERVICES, YOU ARE ACCEPTING AND AGREEING TO ALL OF THESE TERMS AND CONDITIONS, INCLUDING THE MANDATORY MEDIATION AND ARBITRATION PROVISIONS SET OUT IN SECTION 10.0.I. THE COMPANY RESERVES THE RIGHT TO CHANGE THESE TERMS AND CONDITIONS AT ANY TIME WITHOUT NOTICE. ANY CHANGE TO THESE TERMS AND CONDITIONS SHALL BE EFFECTIVE IMMEDIATELY. YOU ARE RESPONSIBLE FOR FOLLOWING ANY CHANGES TO THE TERMS AND CONDITIONS. YOU SHOULD CONTINUE TO REVIEW THE TERMS AND CONDITIONS EACH TIME YOU ACCESS OUR WEBSITE AND USE OUR SERVICES. IF AT ANY TIME YOU DO NOT AGREE TO ANY OF THE TERMS AND CONDITIONS, EXIT THE WEBSITE AND DISCONTINUE USE OF THE WEBSITE AND OUR SERVICES. ANY REQUEST BY YOU OR ANY THIRD PARTY TO AMEND OR CHANGE OUR TERMS AND CONDITIONS IS EXPRESSLY REJECTED. BY ELECTRONICALLY ACCEPTING THESE TERMS AND CONDITIONS, YOU ARE ACKNOWLEDGING THAT YOU HAVE READ, UNDERSTAND AND ARE AGREEING TO ALL OF THESE TERMS AND CONDITIONS.</p>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-primary waves-effect waves-light" onclick="showPart1();">Next</button>
      </div>
    </div>
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div>